version: "3.8"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: pix-hub-app
    restart: unless-stopped
    working_dir: /var/www/src
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - pix-hub-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: pix-hub-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pix-hub-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: pix-hub-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-pix_hub}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-pix_hub}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pix-hub-network

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: pix-hub-worker
    restart: unless-stopped
    working_dir: /var/www/src
    volumes:
      - ./:/var/www
    networks:
      - pix-hub-network
    depends_on:
      - app
      - mysql

networks:
  pix-hub-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
